//USER
export const SET_USER_INFO = "SET_USER_INFO";
export const REMOVE_USER_INFO = "REMOVE_USER_INFO";

//PRODUCTS
export const GET_ACTIVE_PRODUCTS = "GET_ACTIVE_PRODUCTS";
export const GET_ENTIRE_PRODUCTS = "GET_ENTIRE_PRODUCTS";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";


//REPORTS
export const GET_REPORT_DELIVERY = "GET_REPORT_DELIVERY";
export const GET_REPORT_BY_CUSTOMER = "GET_REPORT_BY_CUSTOMER";
export const GET_REPORT_BY_PRODUCT = "GET_REPORT_BY_PRODUCT";
export const GET_REPORT_BY_DATE = "GET_REPORT_BY_DATE";


//ORDER
export const CREATE_ORDER = "CREATE_ORDER";

//DELIVERY
export const GET_SEARCH_RESULT = "GET_SEARCH_RESULT";
export const GET_ORDER_DETAILS = "GET_ORDER_DETAILS";

//CUSTOMER
export const GET_ENTIRE_CUSTOMERS = "GET_ENTIRE_CUSTOMERS";
export const GET_ACTIVE_CUSTOMERS = "GET_ACTIVE_CUSTOMERS";
// export const ADD_CUSTOMER = "ADD_CUSTOMER";
// export const EDIT_CUSTOMER = "EDIT_CUSTOMER";
// export const DELETE_CUSTOMER = "DELETE_CUSTOMER";